### ISSUE TITLE
    Couldn't match expected type `Extension'                 with actual type `KnownExtension'

### ISSUE THREAD

**Issue by agocorona** [pepeiborra/monadloc#2]
GHC 7.6.3
when compiling monadloc-pp at Main.hs

checked with monadLoc 0.6, 0.7,  0.7.1

C:\Users\magocoal\AppData\Roaming\cabal\monadloc-0.7\ghc-7.6.3
Registering monadloc-0.7...
Installed monadloc-0.7
Configuring monadloc-pp-0.2.1...
Building monadloc-pp-0.2.1...
Preprocessing executable 'MonadLoc' for monadloc-pp-0.2.1...
[1 of 1] Compiling Main             ( MonadLoc.hs, dist\build\MonadLoc\MonadLoc-
tmp\Main.o )

MonadLoc.hs:44:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: CPP
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:45:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: MultiParamTypeClasses
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:46:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: FunctionalDependencies
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:47:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: FlexibleContexts
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:48:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: FlexibleInstances
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:49:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: ExplicitForAll
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:50:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: ExistentialQuantification
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:51:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: PatternGuards
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:52:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: ViewPatterns
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:53:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: Arrows
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:54:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: NamedFieldPuns
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:55:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: DisambiguateRecordFields
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:56:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: RecordWildCards
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:57:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: StandaloneDeriving
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:58:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: GeneralizedNewtypeDeriving
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:59:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: ScopedTypeVariables
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:60:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: PatternSignatures
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:61:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: PackageImports
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:62:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: QuasiQuotes
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,
                       ....]}

MonadLoc.hs:63:42:
    Couldn't match expected type `Extension'
                with actual type`KnownExtension'
    In the expression: PostfixOperators
    In the `extensions' field of a record
    In the expression:
      defaultParseMode
        {ignoreLinePragmas = False,
         extensions = [CPP, MultiParamTypeClasses, FunctionalDependencies,

**Comment by pepeiborra** [comment]
Thanks for the report. Unfortunately I can not look at it at the moment, as I haven't still sorted out my ghc after upgrading to Xcode 5. Care to contribute a patch ?

**Comment by pepeiborra** [comment]
Scrap that, I got gcc-clang working with GHC and pushed a patch to make monadloc-pp play with the latest haskell-src-exts.
Now, if only I can figure out how to upgrade my Hackage account in order to update it ...

**Comment by agocorona** [comment]
Hi Pepe:

Thanks a lot!

For the upgrade of hackage account:

https://groups.google.com/forum/#!msg/haskell-cafe/qNhzz84JzQc/9_5abgTAkJMJ

Alberto

2013/11/2 Pepe Iborra notifications@github.com

> Scrap that, I got gcc-clang working with GHC and pushed a patch to make
> monadloc-pp play with the latest haskell-src-exts.
> Now, if only I can figure out how to upgrade my Hackage account in order
> to update it ...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pepeiborra/monadloc/issues/2#issuecomment-27609802
> .

## 

Alberto.
